name: attendance_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  firebase_core: ^3.15.2
  firebase_ml_model_downloader: ^0.3.0

  # Camera & Media
  camera: ^0.11.0+1
  image_picker: ^0.8.7+4
  image: ^4.5.4

  # Charts
  fl_chart: ^1.1.1

  # ML / Face Recognition
  tflite_flutter: ^0.11.0
  # tflite_flutter_helper: ^0.3.1
  google_mlkit_face_detection: ^0.13.1

  # Utilities
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true   # âœ… Add this line
  assets:
    - assets/models/mobile_face_net.tflite
    - assets/rollbook_logo.png
flutter_icons:
  android: true
  ios: true
  image_path: "assets/rollbook_logo.png"